site_name: Thacker Broadcasting Docs
site_url: https://docs.thackerbroadcasting.com
site_author: Thacker Broadcasting
site_description: >-
  Documentation relating to the relating to our site(s), its operations, business operations, legal and product documentation, FAQs, and more of Thacker Broadcasting.

# Navigation
nav:
  - Home: index.md
  - Legal:
      - legal/index.md
      - Disclaimer: legal/disclaimer.md
      - Privacy Policy: legal/privacy-policy.md
      - Terms and Conditions: legal/terms-conditions.md
      - Cookie Policy: legal/cookies.md
      - Refusal of Services: legal/refusal-of-services.md
  - FAQs:
      #- faqs/index.md
      - Can I Have a Local Instance?: faqs/local-instance.md
      - Can I Request to be Hosted in a Different Data Center?: faqs/hosting-change.md
      - How Do I Get My Music?: faqs/music.md
      - How do we Guarantee our Uptime?: faqs/uptime.md
      - What Security Measures are used to Protect me and my Music?: faqs/security-measures.md
#not_in_nav: |
  #/legal

# Repository
repo_name: thackerbroadcasting/docs
repo_url: https://github.com/thackerbroadcasting/docs

# Configs
theme:
  name: material
  custom_dir: src/overrides
  features:
    - navigation.tabs
    #- navigation.tabs.sticky
    - navigation.sections
    - navigation.tracking
    - navigation.top
    - navigation.footer
    #- navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - header.autohide
    - announce.dismiss
    - toc.follow
    #- toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    #- content.code.copy
    - content.action.edit
    - toc.follow
  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
    repo: fontawesome/brands/github
    edit: material/pencil
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night #material/toggle-switch-off-outline
        name: Dark mode
      primary: custom
      accent: amber
    - scheme: slate
      toggle:
        icon: material/weather-sunny #material/toggle-switch
        name: Light mode
      primary: custom
      accent: indigo
  favicon: assets/logo.png
  logo: assets/logo.png
  font:
    text: Archivo
    code: Roboto Mono

copyright: |
  &copy; 2023 Thacker Broadcasting LLC - Broadcasting Beyond • <a href="https://thackerbroadcasting.atlassian.net/servicedesk/customer/portal">Submit a ticket</a> • <a href="#__consent">Change cookie settings</a>

# Plugins
plugins:
  - blog:
      #authors_profiles: true
      authors_file: "{blog}/.authors.yml"
      pagination_format: "$link_first $link_previous ~2~ $link_next $link_last"
      draft_on_serve: false
      archive: true
      archive_name: "Archive"
      archive_date_format: yyyy
      archive_toc: true
      blog_toc: true
      post_date_format: full
      #post_url_date_format: yyyy/MM/dd
      post_url_format: "{slug}"
      #post_excerpt: required

  #- tags:
      #tags_file: tags.md
  - rss:
      match_path: blog/posts/.*
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags
  - search
  #- social
  - git-revision-date-localized:
      enable_creation_date: true
      type: date
  #- git-authors
  - glightbox

# Extra configs
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/thackerbroadcasting
      name: Thacker Broadcasting on Github
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/thackbroadcast
      name: Find us on Twitter
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/thackerbroadcasting
      name: Follow our Facebook
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/thackerbroadcasting
      name: Follow us on Instagram
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/thacker-broadcasting
      name: Thacker Broadcasting on LinkedIn
  generator: false
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    analytics:
      name: Google Analytics
      checked: false
    actions:
      - accept
      - reject
      #- manage

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - md_in_html
  - toc:
      permalink: true
      title: On this page

extra_css:
  - stylesheets/extra.css
